### PR TITLE
[DOCUMENTATION] #28 Add documentation to resolve problems with indexe…

### PR DESCRIPTION
**Pull request by kpurrmann**

### CODE REVIEW

**Comment by pstranghoener** [comment]
@kpurrmann 
I think we shouldn't make it in the documentation. The best way would be we make an option it the extension settings we the index_search can switched on and off and the template is always reacting on the setting. After taht we can make a notice in the documentation that there is an option in the extension settings.

**Comment by kpurrmann** [comment]
@pstranghoener Was my first thought too. But it won't work out of the box. Because I do not know, how the default page is configured in typoscript. Some people name it `page` other one name it `site`. To disable indexing you have to copy the typoscript settings of default page into the pdf page.

**Comment by martin-helmich** [comment]
Does maybe indexed_search offer some kind of extension point that we could use for this? Something like a hook that prevents a page from being indexed or anything similar?

**Comment by kpurrmann** [comment]
@martin-helmich I checked this option the very first time when this bug appeared. Could not find a hook yet. Only way I found was `config.index_enable = 0`.

**Pull request closed without merging**
